### PR TITLE
Remove CVSS v2 prefix from vector string

### LINKED ISSUE #217: osv: CVSS v2 vector string should not include version prefix
_Originally posted by @andrewpollock in https://github.com/ossf/osv-schema/issues/251#issuecomment-2224366177_
 
since #168 is what begat #178 a ~year ago, I figured I'd run this PR over all of the Haskell security advisories, and HSEC-2023-0003 doesn't (to me, legitimately) validate:

```
instance /usr/local/google/home/apollock/gosst/osv/security-advisories/2023/HSEC-2023-0003.json: failed
jsonschema validation failed with 'file:///usr/local/google/home/apollock/gosst/osv/osv-schema/validation/schema.json#'
- at '/affected/0/severity/0': allOf failed
  - at '/affected/0/severity/0/score': 'CVSS:2.0/AV:N/AC:L/Au:N/C:P/I:P/A:P' does not match pattern '^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H'
```

---

This is indeed a bug: the vector string should not include the prefix `CVSS:2.0/`.  (Later versions of CVSS do include the prefix, but CVSS v2 does not).

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change fix the OSV export.

Fixes #217 

## hsec-tools

- [ ] Previous advisories are still valid

### CODE REVIEW

File: code/cvss/test/Spec.hs [hunk 1]
```diff
@@ -4,18 +4,20 @@ module Main where
...
 main = defaultMain $
     testCase "Security.CVSS" $ do
-        forM_ examples $ \(cvssString, score, rating) -> do
-            case CVSS.parseCVSS cvssString of
+        forM_ examples $ \(baseCvssString, score, rating) -> do
+            case CVSS.parseCVSS baseCvssString of
                 Left e -> assertFailure (show e)
                 Right cvss -> do
                     CVSS.cvssScore cvss @?= (rating, score)
+                    let cvssString = Text.replace "CVSS:2.0/" "" baseCvssString
```
Comment (blackheaven) [inline code/cvss/test/Spec.hs:20]:
```suggestion
                    let cvssString = fromMaybe baseCvssString $ Text.stripPrefix "CVSS:2.0/" baseCvssString
```

**Comment by blackheaven** [comment]
I'll handle the CI issue

**Comment by TristanCacqueray** [comment]
Thanks, and I applied the `stripPrefix` suggestion.

File: code/osv/src/Security/OSV.hs [hunk 2]
```diff
@@ -157,7 +157,11 @@ instance Eq Severity where
 instance FromJSON Severity where
   parseJSON = withObject "severity" $ \o -> do
     typ <- o .: "type" :: Parser Text
-    score <- o .: "score" :: Parser Text
+    baseScore <- o .: "score" :: Parser Text
+    let score
+          | -- v2 score does not contain the version prefix
+            typ == "CVSS_V2" = "CVSS:2.0/" <> baseScore
```
[the remark this answers is not in the document]
Comment (TristanCacqueray) [reply code/osv/src/Security/OSV.hs:163]: Right, that was my question. Ok, let me revert back to the first proposal and I'll fix the affected advisory.

**Comment by frasertweedale** [comment]
I'm addressing the CI issues in https://github.com/haskell/security-advisories/pull/220 .

File: code/cvss/src/Security/CVSS.hs [hunk 3]
```diff
@@ -107,16 +107,15 @@ data Metric = Metric
 -- | Parse a CVSS string.
 parseCVSS :: Text -> Either CVSSError CVSS
 parseCVSS txt
-  | "CVSS:3.1/" `Text.isPrefixOf` txt = CVSS CVSS31 <$> validateComponents validateCvss31
-  | "CVSS:3.0/" `Text.isPrefixOf` txt = CVSS CVSS30 <$> validateComponents validateCvss30
-  | "CVSS:2.0/" `Text.isPrefixOf` txt = CVSS CVSS20 <$> validateComponents validateCvss20
-  | otherwise = Left UnknownVersion
+  | "CVSS:3.1/" `Text.isPrefixOf` txt = CVSS CVSS31 <$> validateComponents True validateCvss31
+  | "CVSS:3.0/" `Text.isPrefixOf` txt = CVSS CVSS30 <$> validateComponents True validateCvss30
```
Comment (frasertweedale) [inline code/cvss/src/Security/CVSS.hs:111]: We probably ought to have catch for unknown versions, before the `otherwise` (which infers CVSS v2.0):
```haskell
  | "CVSS:" `Text.isPrefixOf` txt = Left UnknownVersion
```

**Review by frasertweedale — APPROVED** [review]
One suggestion.  And we will also need to rebase on `main` to pick up the CI fixes.

File: code/cvss/src/Security/CVSS.hs (hunk 3 above)
Comment (TristanCacqueray) [reply code/cvss/src/Security/CVSS.hs:111]: Ok, but the `otherwise` branch assumes there is no version prefix, so a v4 string still produces an error:

```haskell
λ> parseCVSS "CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N"
Left Missing value for "CVSS:4.0"
```

**Review by blackheaven — APPROVED** [review]
